version: '3.8'

services:

  rojtari:
    build: .
    container_name: rojtari
    volumes:
      - ./shared_data:/app/shared_data
    ports:
      - "8000:8000"
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always